export const GET_BEERS = 'GET_BEERS';
export const BEERS_REQUEST_SUCCESS = 'BEERS_REQUEST_SUCCESS';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const SEARCH_BEERS = 'SEARCH_BEERS';
export const SEARCH_BEERS_SUCCESS = 'SEARCH_BEERS_SUCCESS';